apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ic-vault-pvc
  namespace: integracentro-prod
  labels:
    app: ic-vault-manager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard