name: IntegraCentro CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-infra:
    name: Validar Terraform y Ansible
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Validar configuración de Terraform
        run: |
          cd infra/terraform/local-minikube
          terraform fmt -check
          terraform init -backend=false
          terraform validate

      - name: Validar sintaxis de Ansible Playbooks
        run: |
          pip install ansible
          ansible-playbook --syntax-check infra/ansible/playbooks/verify_deployment.yml

  build-containers:
    name: Validar Build de Docker Compose
    runs-on: ubuntu-latest
    needs: validate-infra
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Validar compilación de imágenes
        run: |
          docker compose build
